# Generated by Django 2.0 on 2018-08-28 05:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2018, 8, 27))),
                ('content', models.TextField(blank=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('aboutMe', models.TextField(blank=True)),
                ('jobDescription', models.TextField(blank=True)),
                ('field', models.TextField(choices=[('N/A', 'N/A'), ('administration', 'Administration'), ('banking', 'Banking'), ('design', 'Design'), ('education', 'Education'), ('engineering', 'Engineering'), ('entrepreneur', 'Entrepreneur'), ('government', 'Government'), ('health', 'Health'), ('legal', 'Legal'), ('media', 'Media'), ('research', 'Research'), ('sales', 'Sales')], default='N/A')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
